### ISSUE TITLE
PackFix Crashing on Launch

### ISSUE THREAD

**Issue by uchks** [Nilsen84/lcqt2#14]
Launching with PackFix only enabled (JVM args, Custom JVM, mods all disabled) crashes on commit [#14b2a30](https://github.com/Nilsen84/lcqt2/commit/14b2a3085fb82bc44f84cd25e39405204e776617).
[Here's the renderer.log](http://0x0.st/H_XK.log), included is also the error.

```
[2023-08-06 04:24:14.369] [info]  [OUTPUT] [Bridge] Setting Bridge Implementation to com.moonsworth.lunar.HRHOIOOROHIIOIHRCRHIORCCO.ROCHHCRHOICHRHOHHROCOORRI

[2023-08-06 04:24:20.772] [info]  [OUTPUT] Exception in thread "main" java.lang.IllegalStateException: Failed to boot Minecraft
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
Caused by: java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    com/moonsworth/lunar/client/RIRIRCCOOIHIRHIIIRIOIOCIH.OROIHRCIOHCHCICCIICORIRIO(Ljava/lang/String;)Z @2: aload_0
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 04ac 2ac7 0005 04ac 2a12 e3b6 00e8 9a00
    0000010: 0504 acb2 00ea b900 f001 004c 2bb9 00f6
    0000020: 0100 9900 1a2b b900 fa01 00c0 00e5 4d2a
    0000030: 2cb6 00e8 9900 0504 aca7 ffe3 03ac     
  Stackmap Table:
    same_frame(@8)
    same_frame(@19)
    append_frame(@28,Object[#242])
    append_frame(@57,Object[#229])
    chop_frame(@60,1)

	at Genesis//net.minecraft.client.main.Main.redirect$zch000$impl$main$parse(SourceFile:566)
	at Genesis//net.minecraft.client.main.Main.main(SourceFile:53)
	... 5 more

[2023-08-06 04:24:21.070] [info]  JVM exited with code 1
```

For future reference, since this is obviously unreleased anyways, if you don't want me to create an issue / send logs until an update is released, please let me know and I wont in the future.

**Comment by Nilsen84** [comment]
Fixed in 84592ee9f7eef365a406d9e21d9c84c773730011.

> For future reference, since this is obviously unreleased anyways, if you don't want me to create an issue / send logs until an update is released, please let me know and I wont in the future.

Nah I appreciate it haha, would've missed this since I was running on -noverify
